### PR TITLE
Tiled icons, linear progress bar, new options for existing elements, & more

### PR DESCRIPTION
**Pull request by mpaperno**
So yea, this is a huge PR, long time coming, and not really easy to review... sorry!  But here are some things to help comprehend it all (I hope).

The changes are summarized in the new CHANGELOG.md.  I'm calling this v1.2, FWIW.

I did create some tags at a few logical points. Overall the changes build upon each other, so it's basically the same as creating branches, in this case.

Here are some links to comparisons of each tag with the next... FWIW.

[Current main to icon tiling feature](https://github.com/spdermn02/TouchPortal-Dynamic-Icons/compare/main...mp/feature/icon_tiling)

[Icon tiling to adding GPU render setting & option](https://github.com/spdermn02/TouchPortal-Dynamic-Icons/compare/mp/feature/icon_tiling...mp/feature/gpu_render_option)

[GPU render to "new element options"](https://github.com/spdermn02/TouchPortal-Dynamic-Icons/compare/mp/feature/gpu_render_option...mp/feature/new_element_options) - there's a bunch of refactoring here before getting to the actual new features. I ran some benchmarks, and, well... things got distracted for bit.  :)

[New options to new Liner Progress Bar element](https://github.com/spdermn02/TouchPortal-Dynamic-Icons/compare/mp/feature/new_element_options...mp/feature/linear_prog_bar) - this also includes changes to entry.tp generator for the previous new element options.

Here's a screenshot of a test page showing a bunch of progress-bar-style images, knob, and bar graph spread out over multiple button tiles (left and middle), a "speed" indicator using dynamic image names (each digit is an image), and a test with variable size rectangle and shadows. The bars in the middle area are drawn using the new "linear progress bar" action/element, except first green/red one which is all images (and the blue one has an image overlaying a progress bar).

 I'll post the page export once I get it cleaned up a bit and all the images together.

### CODE REVIEW

**Comment by mpaperno** [comment]
Added fixes for Linux and Mac builds. Not just the startup command in entry.tp was wrong, but also the VIPS libs were missing, at least on my installs... and when researching this I saw a lot of lib version mismatch issues ppl were having, so seems better to ship the latest version with the plugin vs. relying on user to install it themselves (or possibly already have some old version).

**Review by spdermn02 — APPROVED** [review]

**Comment by spdermn02** [comment]
looks great - just need to resolve the minor conflicts with main (after the v1.1.0 release) and then we should be good to merge and release and alpha to test with. Thanks for all your improvements Max!

**Comment by mpaperno** [comment]
Cool!  Rebased to resolve the conflict (you'll need to force pull if already pulled this branch). And a few small updates.  I think it's GtG...

Thanks!

**Comment by spdermn02** [comment]
great updates - looks good to me! - thanks again for the work. this plugin expanded way further than I think I expected.

**Pull request merged**
